---
# Source: guestbook/templates/guestbook-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: my-guestbook
  labels:
    app.kubernetes.io/name: guestbook
    helm.sh/chart: guestbook-0.2.0
    app.kubernetes.io/instance: my-guestbook
    app.kubernetes.io/managed-by: Helm
spec:
  type: LoadBalancer
  ports:
  - port: 3000
    targetPort: http-server
  selector:
    app.kubernetes.io/name: guestbook
    app.kubernetes.io/instance: my-guestbook
---
# Source: guestbook/templates/redis-master-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: redis-master
  labels:
    app: redis
    role: master
spec:
  ports:
  - port: 6379
    targetPort: redis-server
  selector:
    app: redis
    role: master
---
# Source: guestbook/templates/redis-slave-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: redis-slave
  labels:
    app: redis
    role: slave
spec:
  ports:
  - port: 6379
    targetPort: redis-server
  selector:
    app: redis
    role: slave
---
# Source: guestbook/templates/guestbook-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-guestbook
  labels:
    app.kubernetes.io/name: guestbook
    helm.sh/chart: guestbook-0.2.0
    app.kubernetes.io/instance: my-guestbook
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: guestbook
      app.kubernetes.io/instance: my-guestbook
  template:
    metadata:
      labels:
        app.kubernetes.io/name: guestbook
        app.kubernetes.io/instance: my-guestbook
    spec:
      containers:
      - name: guestbook
        image: "resouer/guestbook:v1"
        imagePullPolicy: Always
        ports:
        - name: http-server
          containerPort: 3000
---
# Source: guestbook/templates/redis-master-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-master
  labels:
    app: redis
    role: master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
      role: master
  template:
    metadata:
      labels:
        app: redis
        role: master
    spec:
      containers:
      - name: redis-master
        image: redis:2.8.23
        ports:
        - name: redis-server
          containerPort: 6379
---
# Source: guestbook/templates/redis-slave-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-slave
  labels:
    app: redis
    role: slave
spec:
  replicas: 2
  selector:
    matchLabels:
      app: redis
      role: slave
  template:
    metadata:
      labels:
        app: redis
        role: slave
    spec:
      containers:
      - name: redis-slave
        image: resouer/redis-slave:v2
        ports:
        - name: redis-server
          containerPort: 6379
---
# Source: temp/templates/add_res/config-map.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: game-demo
data:
  # property-like keys; each key maps to a simple value
  player_initial_lives: "3"
  ui_properties_file_name: "user-interface.properties"

  # file-like keys
  game.properties: |
    enemy.types=aliens,monsters
    player.maximum-lives=10    
  user-interface.properties: |
    color.good=purple
    color.bad=yellow
    allow.textmode=true  
  url: preview.example.com
---
# Source: temp/templates/add_res/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minimal-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx-example
  rules:
  - http:
      paths:
      - path: preview.example.com/testpath
        pathType: Prefix
        backend:
          service:
            name: test
            port:
              number: 80
---
# Source: temp/templates/add_res/sealed-secret.yaml
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mysecret
  namespace: mynamespace
spec:
  encryptedData:
    foo: AgBy3i4OJSWK+PiTySYZZA9rO43cGDEq.....
